CREATE TABLE [dbo].[Menu](
    [MenuID] [int] NOT NULL,
    [FromDate] [date] NOT NULL,
    [ToDate] [date] NOT NULL,
 CONSTRAINT [PK_Menu1] PRIMARY KEY CLUSTERED 
(
    [MenuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[Menu]  WITH CHECK ADD  CONSTRAINT [CK_Menu1] CHECK  (([FromDate]<[ToDate]))
GO
ALTER TABLE [dbo].[Menu] CHECK CONSTRAINT [CK_Menu1]

